import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Aleo } from "next/font/google";
import "./globals.css";
import Navbar from "../Components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const aleo = Aleo({
  variable: "--font-aleo",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

/** Same asset as navbar; used for tab / PWA icons (replaces default favicon). */
const SITE_ICON = "/assets/images/FAM Approved Logo 4-Feb-2026.png";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: SITE_ICON, type: "image/png" }],
    apple: [{ url: SITE_ICON, type: "image/png" }],
    shortcut: SITE_ICON,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${aleo.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
